### ISSUE TITLE
Changes to Vorbis comments mess up the header info

### ISSUE THREAD

**Issue by chrilleferna** [DarrenKirby/flacinfo-rb#2] opened 2015-01-01 22:29 UTC
When deleting or adding a tag in the Vorbis comment it appears that the Vorbis comment header becomes erraneous and can't be correctly parsed.

In my Rails console I did this:

    require "flacinfo"
    theDir = Rails.root.to_s + "/public/system/recordings"
    fi1=FlacInfo.new(theDir+"/kalle.flac")
    fi1.comment

    fi1.comment_del("ARTIST")
    fi1.comment
    fi1.update!

Update! raises an error in parse_flac_meta_blocks. I have tracked it down to the value of the type variable, which was 127 in the test
    if type >= typetable.size …

I have traced the values of the vcd and vch just before and after deleting a tag. It looks like this:

    irb(main):017:0* finfo.comment_del("ARTIST")
    Before:
    vcd = " \x00\x00\x00reference libFLAC 1.3.0 20130526\x03\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998N\x00\x00\x00ARTIST=Malm\xC3\xB6 Symphony Orchestra. Miah Persson (soprano). Lan Shui (conductor)"
    
    vch = "\x04\x00\x00\x98"
    
    After:
    
    vcd = " \x00\x00\x00reference libFLAC 1.3.0 20130526\x02\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998"
    
    vch = "\x04\x00\x00F"
    => true

**Comment by DarrenKirby** [comment] 2015-01-07 14:38
Thanks, will look into this.

**Comment by DarrenKirby** [comment] 2015-01-10 05:32
Hi Christer,

Have been playing with this for a while, and unfortuneately I have not been able to reproduce your error using any of the flac files I have on hand here. I even tried several with 'special' (non-ascii) characters in the vorbis comments.

Even odder is that the values you posted for vch and vcd are 'correct' both before, and after you deleted the comment. Here's a sample irb session where I have 'decoded' the strings exactly as in FlacInfo itself:

Before deleting the comment:
```ruby
>  vch = "\x04\x00\x00\x98"
=> "\x04\x00\x00\x98"
> block_header = vch[0].unpack("B*")[0]
=> "00000100"
> lastheader = block_header[0].to_i & 1
=> 0 # It's not the last header block in the file
> type = sprintf("%u", "0b#{block_header[1..7]}").to_i
=> 4 # '4' is the type value for VORBIS_COMMENT as per the flac spec
> block_size = vch[1,3].unpack("B*")[0].to_i(2)
=> 152 # the size of the comments as reported by the block-header is 152 bytes
> vcd = " \x00\x00\x00reference libFLAC 1.3.0 20130526\x03\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998N\x00\x00\x00ARTIST=Malm\xC3\xB6 Symphony Orchestra. Miah Persson (soprano). Lan Shui (conductor)"
=> " \x00\x00\x00reference libFLAC 1.3.0 20130526\x03\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998N\x00\x00\x00ARTIST=Malm\xC3\xB6 Symphony Orchestra. Miah Persson (soprano). Lan Shui (conductor)"
> vcd.length
=> 152 # and Ruby agrees...
```
And now after deleting the 'ARTIST' tag...

```ruby
> vch = "\x04\x00\x00F"
=> "\x04\x00\x00F"
> block_header = vch[0].unpack("B*")[0]
=> "00000100"
> lastheader = block_header[0].to_i & 1
=> 0 # still not the last header
> type = sprintf("%u", "0b#{block_header[1..7]}").to_i
=> 4 # still a VORBIS_COMMENT
> block_size = vch[1,3].unpack("B*")[0].to_i(2)
=> 70 # header now reporting the comment block as 70 bytes
> vcd = " \x00\x00\x00reference libFLAC 1.3.0 20130526\x02\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998"
=> " \x00\x00\x00reference libFLAC 1.3.0 20130526\x02\x00\x00\x00\r\x00\x00\x00TRACKNUMBER=2\t\x00\x00\x00DATE=1998"
> vcd.length
=> 70 # and indeed it is 70 bytes
```

so...not sure what to tell you, it appears the new comment block and header got written to the file correctly.

You said:

> I have tracked it down to the value of the type variable, which was 127 in the test

'127' is listed in the flac spec as 'invalid' for block types. I have no idea why it is reading this value, as FlacInfo would never write this value as a block type. Is there some other program messing with your flac files? Are you getting the same error with several different flacs? Or just this one?

Is another program such as metaflac able to read/write the file correctly?

In any event, I cannot do much for you if I cannot reproduce the error. If you are absolutely sure it is FlacInfo that is messing up, then I guess you will have to email me the flac file that is breaking things...

**Comment by chrilleferna** [comment] 2015-01-10 12:54
Hi Darren,
Thanks for looking into this. I've done some more tests and found that the problem appears when the flac files have been created by Audacity (version 2.0.6 on an oldish iMac with OSX 10.4.11). This happens regardless of weather there is is a VORBIS comment or not in the file (i.e. adding a comment creates the error).

However, flac files created by xACT (version 2.35 on OSX 10.8.5)) work perfectly OK!!! 

Looking at the meta-data one can see that Audacity 2.0.6 uses libFLAC verson 1.3.0 and xACT uses version 1.3.1. Maybe the problem is related to a specific version of libFLAC used for the encoding? Or maybe the fairly old version of Audacity just creates crappy flac files.

Anyway, I will re-encode my files with xACT, so hopefully everything will work out for me.

Thanks again
  -- christer

**Comment by DarrenKirby** [comment] 2015-01-14 06:15
OK, will close this issue for now. Please do open another in future if you find a bug in the library.
Cheers.

**Closed by DarrenKirby** 2015-01-14 06:15 UTC
